### ISSUE TITLE
Is this possible? or move to feature request.

### ISSUE THREAD

**Issue by chaz7201** [Phrynohyas/eve-o-preview#102] opened 2018-01-12 22:45 UTC
Recently with the changes made to eve the clients use alot more cpu when running multipul accounts. This is diverted by minimizing the window. The client will go from 20% cpu to 3%.

Is there a way to minimize the windows that are not on focus automatically?

ie. Char1 Char2 and Char3. When switching from Char1 to Char3 by clicking on the preview, the program will minimize Char1 and bring Char3 to foreground?
Char2 however would need to always be exempt for minimizing for "intel" or "reasons".
 
I used to run 6 chars fine. However now the cpu is at 99% all the time. Minimizing them solves this issue but really slows down the process to switch between accounts.

**Comment by Phrynohyas** [comment] 2018-01-15 14:05
This is a new feaature. Seems interesting in terms of QOL so will be implemented in the next release

**Comment by Phrynohyas** [comment] 2018-02-25 20:51
Duplicate of https://github.com/Phrynohyas/eve-o-preview/issues/63

**Closed as completed by Phrynohyas** 2018-02-25 20:51 UTC
Labels: duplicate
