### ISSUE TITLE
[Bug] Previews hide when checkbox "Previews always on top" is unchecked

### ISSUE THREAD

**Issue by RmzVoid** [Phrynohyas/eve-o-preview#158] opened 2020-05-02 11:38 UTC
Please check that screenshots

https://cdn.discordapp.com/attachments/540865738941136916/706105268513144842/unknown.png

https://cdn.discordapp.com/attachments/540865738941136916/706105315011199026/unknown.png

I don't want previews allways on top, but can't turn off that option because previews just disappear.

I have two monitors. On the main monitor I run two eve windows in background and want to have two previews on the second monitor. But sometimes I need to perform some actions with another windows on the second monitor and I can't because they are behind previews.

**Comment by Phrynohyas** [comment] 2021-05-02 16:47
Apparently a duplicate of #189

**Closed as completed by Phrynohyas** 2021-05-02 16:47 UTC
Labels: bug, duplicate
